// Warm, the first theme (CHK-10): cream and warm ink, one strong accent (coral) and sun yellow for
// Game Challenges only. Seeds and reasoning: docs/design-system/foundations.md.
import {
  amber,
  blue,
  coral,
  cream,
  fontFamily,
  green,
  ink,
  olive,
  plum,
  radius,
  rose,
  sun,
  teal,
  violet,
  white,
} from '../primitives.ts';
import type { Theme } from '../semantic.ts';

export const warm = {
  name: 'warm',
  modes: {
    light: {
      background: cream[50],
      foreground: ink[900],
      card: white,
      'card-foreground': ink[900],
      popover: white,
      'popover-foreground': ink[900],
      primary: coral[600],
      'primary-foreground': white,
      secondary: cream[100],
      'secondary-foreground': ink[900],
      muted: cream[100],
      'muted-foreground': ink[600],
      accent: coral[100],
      'accent-foreground': coral[800],
      destructive: rose[700],
      border: cream[200],
      input: ink[500],
      ring: coral[600],

      // Deeper than `background`, so white bubbles stand out (screen map, design note 1).
      'chat-background': cream[100],
      'bubble-own': coral[600],
      'bubble-own-foreground': white,
      'bubble-other': white,
      'bubble-other-foreground': ink[900],
      challenge: sun[200],
      'challenge-foreground': sun[900],
      'presence-online': green[600],
      unread: coral[600],
      'unread-foreground': white,
      mention: coral[600],
      'mention-foreground': white,
      'participant-1': rose[800],
      'participant-2': teal[700],
      'participant-3': amber[800],
      'participant-4': blue[800],
      'participant-5': green[800],
      'participant-6': plum[700],
      'participant-7': olive[700],
      'participant-8': violet[800],
      success: green[700],
      'success-foreground': white,
      // Not sun: sun yellow means a Game Challenge (screen map, design note 3).
      warning: amber[700],
      'warning-foreground': white,
      danger: rose[700],
      'danger-foreground': white,
      info: blue[700],
      'info-foreground': white,
    },
    dark: {
      background: ink[950],
      foreground: ink[50],
      card: ink[900],
      'card-foreground': ink[50],
      popover: ink[900],
      'popover-foreground': ink[50],
      primary: coral[400],
      'primary-foreground': ink[950],
      secondary: ink[800],
      'secondary-foreground': ink[50],
      muted: ink[900],
      'muted-foreground': ink[300],
      accent: coral[950],
      'accent-foreground': coral[100],
      destructive: rose[400],
      border: ink[800],
      input: ink[500],
      ring: coral[400],

      'chat-background': ink[950],
      // Deeper than `primary`, so a Chat isn't a wall of bright coral at night (design note 2).
      'bubble-own': coral[700],
      'bubble-own-foreground': coral[50],
      'bubble-other': ink[900],
      'bubble-other-foreground': ink[50],
      challenge: sun[300],
      'challenge-foreground': sun[950],
      'presence-online': green[400],
      unread: coral[400],
      'unread-foreground': ink[950],
      mention: coral[400],
      'mention-foreground': ink[950],
      'participant-1': rose[200],
      'participant-2': teal[200],
      'participant-3': amber[300],
      'participant-4': blue[300],
      'participant-5': green[300],
      'participant-6': plum[300],
      'participant-7': olive[200],
      'participant-8': violet[400],
      success: green[400],
      'success-foreground': ink[950],
      warning: amber[400],
      'warning-foreground': ink[950],
      danger: rose[400],
      'danger-foreground': ink[950],
      info: blue[400],
      'info-foreground': ink[950],
    },
  },
  shape: {
    // Message bubbles: 20px, with the corner nearest the author at 6px (the "tail").
    'radius-bubble': radius['2xl'],
    'radius-bubble-tail': radius.sm,
    'radius-card': radius.xl,
    'radius-pill': radius.full,
    'font-sans': fontFamily.nunito,
    'font-mono': fontFamily.jetbrainsMono,
  },
} as const satisfies Theme;
